### ISSUE TITLE
Problemas con la distribucion

### ISSUE THREAD

**Issue by LeandroLuque** [LeandroLuque/tpfinalmodelos#1]
Hola! Tenemos un problema con la distribucion de los pacientes. Todos llegan despues que el quirofano abren, con lo cual cuando se procesa el evento de abrir quirofano y se quiere tomar los pacientes de la cola de espera de operacion, no hay nadie. El problema esta en como nos damos cuenta desques que hay gente para operarse.

**Comment by rhuincalef** [comment]
Hola! Probaste cambiar el valor del reloj a cero cuando lo instancias? Antes de que generes los 10 pacientes iniciales? Asi llegarían todos a penas comienza un nuevo dia
